<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PSK9T3S" failures="1" tests="1" name="Default test" time="90.697" errors="0" timestamp="2023-09-07T18:52:28 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="73.118">
    <failure type="java.lang.AssertionError" message="expected [Karthikeyan] but found [987456321023]">
      <![CDATA[java.lang.AssertionError: expected [Karthikeyan] but found [987456321023]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.AdditionalCustomerInfo_Steps.user_verify_the_same_record_got_saved_in_screen(AdditionalCustomerInfo_Steps.java:616)
at âœ½.user verify the same record got saved in screen(file:///C:/Users/inindc00606/git/KarthikeyanIjara/Ijara_Karthi2/src/test/java/features/Ijarah_AdditionalCustomerInfo.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
